name: build images

on:
  push:
    paths:
        - 'bionconductor_packages.txt'
        - 'CRAN_packages.txt'
        - 'devtools_packages.txt'
        - 'Dockerfile'
        - 'install_packages.R'
  release:
  workflow_dispatch:


jobs:
  amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - btrspg/dev-env-image:latest-ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Docker daemon.json
        run: |
          sudo mkdir -p /mnt/docker
          sudo chmod 777 /mnt/docker
          sudo mkdir -p /etc/docker
          sudo cp daemon.json /etc/docker/daemon.json 
      - name: Restart Docker service
        run: |
          sudo docker info
          sudo systemctl restart docker
          sudo docker info
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DH_USER }}/${{ github.event.repository.name }}
          tags: |
            type=ref,event=branch,enable=${{ github.ref != 'refs/heads/main' }}
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: IMAGE=${{ matrix.image }}
      